# description: Where to import from
# type: string
# required: true
src: ./seeds/pulumi-examples/

# description: name of vault to import into
# type: string
# required: true
vaultName: vault

# description: whether to concatenate everything into one note
# type: boolean
# concatenate: TODO

# description: whether to ignore a given file
# type: boolean
# ignore: TODO

# description: If concatenate is set, name of destination path
# type: string
# destName: TODO

fnameAsId: true
noAddUUID: true
indexName: readme

frontmatter:
  gitNotePath: '{{ noteHiearchy }}/README.md'
  sources:
    - name: 'pulumi examples'
      url: 'https://github.com/pulumi/examples'
      license: Apache License 2.0